---
- name: Get host IP address
  ansible.builtin.command: "hostname -I"
  register: ip_address

- name: Create DNS record for host
  ansible.windows.win_dns_record:
    name: "{{ inventory_hostname }}"
    zone: "infrahero.co.uk"
    type: A
    value: "{{ ip_address.stdout.split()[0] }}"