---
- name: Test Webhook from Netbox
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: Debug DNS Record
      debug:
        msg: "Zone: {{ netbox_data.zone.name }}\nName: {{ netbox_data.name }}\nValue: {{ netbox_data.value }}"

    - name: Add DNS Record to Domain Controller DNS
      win_dns_record:
        name: "{{ netbox_data.name }}"
        value: "{{ netbox_data.value }}"
        type: A
        zone: "{{ netbox_data.zone.name }}"
        state: present
      delegate_to: infdc01.hq.infrahero.co.uk
