---
- name: Get host IP address
  ansible.builtin.command: "hostname -I"
  register: ip_address

- name: Create DNS record for host
  ansible.windows.win_dns_record:
    name: "{{ inventory_hostname }}"
    zone: "hq.infrahero.co.uk"
    type: A
    value: "{{ ip_address.stdout }}"

- name: Update Netbox
  netbox.netbox.netbox_dns_record:
    netbox_url: "https://netbox.hq.infrahero.co.uk"
    netbox_token: ""
    state: present
    dns_zone: "hq.infrahero.co.uk"
    name: "{{ inventory_hostname }}"
    type: A
    value: "{{ ip_address.stdout }}"
