all:
  children:
    linux:
      children:
        k8s:
          hosts:
            k8s-controlplane.hq.infrahero.co.uk: {}
            k8s-worker-01.hq.infrahero.co.uk: {}
            k8s-worker-02.hq.infrahero.co.uk: {}
      hosts:
        authentik.hq.infrahero.co.uk: {}
        bunkerweb.hq.infrahero.co.uk: {}
        gitea.hq.infrahero.co.uk: {}
        gns3.hq.infrahero.co.uk: {}
        minestom.hq.infrahero.co.uk: {}
        netbox.hq.infrahero.co.uk: {}
        nextexplorer.hq.infrahero.co.uk: {}
        openclaw.hq.infrahero.co.uk: {}
        powerdns.hq.infrahero.co.uk: {}
        teleport.hq.infrahero.co.uk: {}
        teleport-wds.hq.infrahero.co.uk: {}
        terraform-agent.hq.infrahero.co.uk: {}
        traefik.hq.infrahero.co.uk: {}
        skylite.hq.infrahero.co.uk: {}
        containerlab.hq.infrahero.co.uk: {}
    firewalls:
      children:
        perimeter:
          hosts:
            opnsense-mgt.hq.infrahero.co.uk: {}
      children:
        internal:
          hosts:
            infrahero-pa-01-mgt.hq.infrahero.co.uk: {}
    windows:
      hosts:
        infdc01.hq.infrahero.co.uk: {}
        infdhcp01.hq.infrahero.co.uk: {}
        infmgt01.hq.infrahero.co.uk: {}

