---
- name: Grab LSB Release from shell
  shell: lsb_release -cs
  register: lsb_release

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "10.0.10.33 puppet-master-01.hq.infrahero.co.uk puppet"
    state: present

- name: Download latest .deb package
  get_url:
    url: "https://apt.puppet.com/puppet7-release-{{ lsb_release.stdout }}.deb"
    dest: /tmp/puppet-agent.deb

- name: Install puppet7-release .deb package
  apt:
    deb: /tmp/puppet-agent.deb
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install Puppet Agent
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Update puppet.conf file
  blockinfile:
    path: /etc/puppet/puppet.conf
    block: |
      [main]
      certname = "{{ inventory_hostname }}"
      server = puppet-master-01.hq.infrahero.co.uk

      [agent]
      runinterval = 5m
    state: present

- name: Make a certificate request
  command: sudo /usr/bin/puppet agent -t --server puppet-master-01.hq.infrahero.co.uk
  register: puppet_agent_test

- name: Approve the certificate request
  command: sudo /usr/bin/puppetserver ca sign "{{ inventory_hostname }}"
  when: puppet_agent_test.changed
  delegate_to: puppet-master-01.hq.infrahero.co.uk
