---

- name: Create Temp Directory for Wazuh Agent MSI
  ansible.windows.win_file:
    path: C:\Temp
    state: directory

- name: Download Wazuh Agent on Windows Devices
  ansible.windows.win_get_url:
    url: https://packages.wazuh.com/4.x/windows/wazuh-agent-4.14.4-1.msi
    dest: C:\Temp\wazuh-agent-4.14.4-1.msi

- name: Install Wazuh Agent on Windows Devices
  ansible.windows.win_package:
    path: C:\Temp\wazuh-agent-4.14.4-1.msi
    state: present
    arguments:
      - MANAGER='{{ wazuh_manager_ip }}'

- name: Update ossec.conf with Wazuh manager IP address on Windows Devices
  ansible.windows.win_xml:
    path: C:\Program Files (x86)\ossec-agent\ossec.conf
    xpath: //client/manager
    value: '{{ wazuh_manager_ip }}'

- name: Start Wazuh Agent Service on Windows Devices
  ansible.windows.win_service:
    name: WazuhSvc
    start_mode: auto
    state: started
